// <auto-generated />
using AmpPromatic.CNCRefactor.Desktop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmpPromatic.CNCRefactor.Desktop.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250131202037_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("AmpPromatic.CNCRefactor.Desktop.Data.Insertion", b =>
                {
                    b.Property<int>("InsertionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InsertionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Qualifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InsertionId");

                    b.HasIndex("MachineId");

                    b.ToTable("Insertions");
                });

            modelBuilder.Entity("AmpPromatic.CNCRefactor.Desktop.Data.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("AmpPromatic.CNCRefactor.Desktop.Data.Removal", b =>
                {
                    b.Property<int>("RemovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RemovalId");

                    b.HasIndex("MachineId");

                    b.ToTable("Removals");
                });

            modelBuilder.Entity("AmpPromatic.CNCRefactor.Desktop.Data.Replacement", b =>
                {
                    b.Property<int>("ReplacementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextToReplace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReplacementId");

                    b.HasIndex("MachineId");

                    b.ToTable("Replacements");
                });

            modelBuilder.Entity("AmpPromatic.CNCRefactor.Desktop.Data.Insertion", b =>
                {
                    b.HasOne("AmpPromatic.CNCRefactor.Desktop.Data.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AmpPromatic.CNCRefactor.Desktop.Data.Removal", b =>
                {
                    b.HasOne("AmpPromatic.CNCRefactor.Desktop.Data.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AmpPromatic.CNCRefactor.Desktop.Data.Replacement", b =>
                {
                    b.HasOne("AmpPromatic.CNCRefactor.Desktop.Data.Machine", "Machine")
                        .WithMany("Replacements")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AmpPromatic.CNCRefactor.Desktop.Data.Machine", b =>
                {
                    b.Navigation("Replacements");
                });
#pragma warning restore 612, 618
        }
    }
}
